# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import primefactor_pb2 as primefactor__pb2


class FactorsStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.PrimeFactors = channel.unary_unary(
        '/primefactor.Factors/PrimeFactors',
        request_serializer=primefactor__pb2.Request.SerializeToString,
        response_deserializer=primefactor__pb2.Response.FromString,
        )


class FactorsServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def PrimeFactors(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_FactorsServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'PrimeFactors': grpc.unary_unary_rpc_method_handler(
          servicer.PrimeFactors,
          request_deserializer=primefactor__pb2.Request.FromString,
          response_serializer=primefactor__pb2.Response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'primefactor.Factors', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
